version: '3'

services:
  postgres:
    image: bitnami/postgresql
    container_name: dev-finance
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=dev
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=finance